name: Archive validation
on:
  pull_request:
  push:
    branches: [master]
permissions:
  contents: read
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - run: python3 _admin/scripts/validate_archive.py
